
spring.application.name=teamlancer

# DB
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/team_lancer}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

# JWT
app.jwt.secret=${JWT_SECRET:lembrar_o_seu_tonho_e_rafa_a_mudar_isso_aqui_antes_de_rodar}
app.jwt.expiration-ms=3600000
app.jwt.refresh-expiration-ms=604800000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

spring.profiles.active=local