spring.datasource.url=jdbc:postgresql://localhost:5432/team_lancer
spring.datasource.username=USER_FODA
spring.datasource.password=SENHA_FODA

app.jwt.secret=IYk4FUYkxracHrvnMtXwE/EXFMqpf1gLLsHjv6OgJ/qMWkKdXFmHtnVf2+7RGqEAtf/IxxVYbg+Eb7dxVJbVGg==
spring.jpa.show-sql=true
